improve script and add new function

diff --git a/bash/ftp-dobby b/bash/ftp-dobby
--- a/bash/ftp-dobby
+++ b/bash/ftp-dobby
@@ -1,33 +1,37 @@
 #!/usr/bin/env bash
 
+password=
+
 get-ftp-password() {
-    local user=$1
-    local password=""
-    while fid= read -r line; do
-        set -- $line
-        if [ "$1" = "$user" ]; then
-            password=$2
-            break
+    local ftp_user ftp_pwd
+    while read -r ftp_user ftp_pwd; do
+        if [[ "$ftp_user" = "$1" ]]; then
+            password="$ftp_pwd"
+            return
         fi
-    done < $HOME/.ftp_passwords
-    echo "$password"
+    done <"$HOME/.ftp_passwords"
+    echo "Could not find password for user $1"
+    exit 1
+}
+
+print-ftp-list() {
+    local ftp_user ftp_pwd
+    while read -r ftp_user ftp_pwd; do
+        echo "$ftp_user"
+    done <"$HOME/.ftp_passwords"
 }
 
 ftp-connect() {
     local user=$1
-    local password=$(get-ftp-password "$user")
-    if [ -z "$password" ]; then
-        echo "No password found for user $user"
-    else
-        lftp geo10.elie.ucl.ac.be -u "$user","$password"
-    fi
+    get-ftp-password "$user"
+    lftp geo10.elie.ucl.ac.be -u "$user","$password"
 }
 
 ftp-download() {
-    local user path password my_cmd
+    local user path my_cmd
     local ftp_path is_file
     if [[ $# == 1 ]]; then
-        # Assume it is a file 
+        # Assume it is a file
         is_file=true
         ftp_path="$1"
     elif [[ $# == 2 && $1 == "-r" ]]; then
@@ -39,12 +43,8 @@ ftp-download() {
         exit 1
     fi
 
-    IFS=":" read -r user path <<< "$ftp_path"
-    password=$(get-ftp-password $user)
-    if [ -z "$password" ]; then
-        echo "Password for user $user not found"
-        exit 1
-    fi
+    IFS=":" read -r user path <<<"$ftp_path"
+    get-ftp-password "$user"
 
     if $is_file; then
         my_cmd="get $path; exit"
@@ -52,7 +52,7 @@ ftp-download() {
         my_cmd="mirror $path; exit"
     fi
 
-    lftp -u $user,$password -e "$my_cmd" geo10.elie.ucl.ac.be
+    lftp -u "$user,$password" -e "$my_cmd" geo10.elie.ucl.ac.be
 }
 
 ftp-upload() {
@@ -62,7 +62,7 @@ ftp-upload() {
     local destination=
     local my_command=
     for arg in "$@"; do
-        if (( i == $# - 1 )); then
+        if ((i == $# - 1)); then
             destination="$arg"
         elif [[ -d $arg ]]; then
             dir_list+=("$arg")
@@ -75,16 +75,11 @@ ftp-upload() {
         ((i++))
     done
 
-    IFS=":" read -r user dst_path <<< "$destination"
-    local password=$(get-ftp-password $user)
+    IFS=":" read -r user dst_path <<<"$destination"
+    get-ftp-password "$user"
 
-    if [ -z "$password" ]; then
-        echo "Password for user $user not found"
-        exit 1
-    fi
-
-    if (( ${#dir_list[@]} == 0 )); then
-        my_command="cd $dst_path; mput ${file_list[@]}; exit"
+    if ((${#dir_list[@]} == 0)); then
+        my_command="cd $dst_path; mput ${file_list[*]}; exit"
     else
         my_command="mirror -R"
         for dir in "${dir_list[@]}"; do
@@ -96,21 +91,27 @@ ftp-upload() {
         my_command+=" -O $dst_path; exit"
     fi
 
-    lftp -u $user,$password -e "$my_command" geo10.elie.ucl.ac.be
+    lftp -u "$user,$password" -e "$my_command" geo10.elie.ucl.ac.be
 }
 
 main() {
     case $1 in
-        "upload")
-            ftp-upload "${@:2}";;
-        "download")
-            ftp-download "${@:2}";;
-        "connect")
-            ftp-connect "$2";;
-        *)
-            echo "Usage: $0 {upload|download|connect}"
-            exit 1
-            ;;
+    "upload")
+        ftp-upload "${@:2}"
+        ;;
+    "download")
+        ftp-download "${@:2}"
+        ;;
+    "connect")
+        ftp-connect "$2"
+        ;;
+    "list")
+        print-ftp-list
+        ;;
+    *)
+        echo "Usage: $0 {upload|download|connect}"
+        exit 1
+        ;;
     esac
 }
 
