ftp-upload should deal with wildcard extension

diff --git a/bash/ftp-upload b/bash/ftp-upload
--- a/bash/ftp-upload
+++ b/bash/ftp-upload
@@ -1,7 +1,24 @@
 #!/bin/bash
 
-src_path=$1
-user_path=( $(echo $2 | tr ':' ' ') )
+dir_list=()
+file_list=()
+i=0
+destination=
+for arg in "$@"; do
+    if (( i == $# - 1 )); then
+        destination="$arg"
+    elif [[ -d $arg ]]; then
+        dir_list+=("$arg")
+    elif [[ -f $arg ]]; then
+        file_list+=("$arg")
+    else
+        echo "Invalid argument: $arg"
+        exit 1
+    fi
+    ((i++))
+done
+
+user_path=( $(echo $destination | tr ':' ' ') )
 user=${user_path[0]}
 dst_path=${user_path[1]}
 password=$(get_ftp_password $user)
@@ -11,10 +28,17 @@ if [ -z "$password" ]; then
     exit 1
 fi
 
-if [ -d "$src_path" ]; then
-    my_command="mirror -R $src_path $dst_path; exit"
+if (( ${#dir_list[@]} == 0 )); then
+    my_command="cd $dst_path; mput ${file_list[@]}; exit"
 else
-    my_command="cd $dst_path; mput $src_path; exit"
+    my_command="mirror -R"
+    for dir in "${dir_list[@]}"; do
+        my_command+=" -F $dir"
+    done
+    for file in "${file_list[@]}"; do
+        my_command+=" -f $file"
+    done
+    my_command+=" -O $dst_path; exit"
 fi
 
 lftp -u $user,$password -e "$my_command" geo10.elie.ucl.ac.be
